### ISSUE TITLE
`__file__` not defined both in script and in shell

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/pyzo#16]
In Pyzo shell could assume same environment as the opened script, if there is any.

Related to #1, #3 and [Benjamin-Loison/cpython/issues/17](https://github.com/Benjamin-Loison/cpython/issues/17).

**Comment by Benjamin-Loison** [comment]
<details>
<summary><code>test.py</code>:</summary>

```python
import os

print(os.getcwd())
print(os.path.dirname(os.path.abspath(__file__)))
print(os.getcwd())
```
</details>
<details>
<summary>Output:</summary>

```
/home/benjamin_loison
Traceback (most recent call last):
  File "/home/benjamin_loison/Desktop/test.py", line 4, in <module>
    print(os.path.dirname(os.path.abspath(__file__)))
                                          ^^^^^^^^
NameError: name '__file__' is not defined. Did you mean: '__name__'?
```
</details>

when executed in Pyzo.

```bash
python3 ~/Desktop/test.py
```
<details>
<summary>Output:</summary>

```
/home/benjamin_loison
/home/benjamin_loison/Desktop
/home/benjamin_loison
```
</details>

**Comment by Benjamin-Loison** [comment]
<details>
<summary><code>test.py</code>:</summary>

```python
import os
import inspect

print(os.getcwd())
print(os.path.dirname(os.path.abspath(inspect.getsourcefile(lambda: 0))))
print(os.getcwd())
```
</details>
<details>
<summary>Output:</summary>

```
/home/benjamin_loison
/home/benjamin_loison/Desktop
/home/benjamin_loison
```
</details>

<details>
<summary>Need to select all lines since the beginning to work, otherwise get:</summary>

```
Traceback (most recent call last):
  File "/home/benjamin_loison/my_folder/my_script.py", line 4, in <module>
    print(abspath(getsourcefile(lambda: 0)))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 418, in abspath
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
</details>

<details>
<summary>This issue was reported by the person:</summary>

```
-----BEGIN PGP MESSAGE-----

hF4DTQa9Wom5MBgSAQdAx/4mKZMReyhxwzHr4F0OA6S+WPNIBzkgEjGVx7FyLF8w
3ouK+PGnm/mk0QD8mTCvx6cFaqHEWkPOZOsesWD0vqpbdSi+I8caShGI1ADXtkVK
1EoBCQIQIXwSR8s4za0V7ta5QI0KZTh9heUulVreWUcK+8AZ8qzqVwqmn2UU2Oxk
IA4T+8fxU6tAaO2Nap/1LXoFRVEAxqn1nSEixw==
=V1iw
-----END PGP MESSAGE-----
```
</details>

on his Linux Mint 22.2 Cinnamon laptop.

<details>
<summary>With <code>my_script.py</code>:</summary>

```python
from inspect import getsourcefile
from os.path import abspath

print(abspath(getsourcefile(lambda: 0)))
```
</details>

This fact does not help `__file__`.

```bash
python3 ~/Desktop/test.py
```
<details>
<summary>Output:</summary>

```
/home/benjamin_loison
/home/benjamin_loison/Desktop
/home/benjamin_loison
```
</details>

**Comment by Benjamin-Loison** [comment]
So have a workaround at least now.

**Comment by Benjamin-Loison** [comment]
So using `os.chdir` seems better as do not face the issue mentioned above with part of the script being selected, or even not saved once file.
